accounts/urls.py
from django.urls import path
from .views import SignUpView, login_view

app_name = "accounts"

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup_view"),
    path("login/", login_view, name="login"),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    # path("", views.PostListView.as_view(), name="post_list"),
    path("new/", views.post_create, name="post_create"),
    path("<int:id>/edit", views.post_update, name="post_edit"),
    path("<int:id>/delete", views.post_delete, name="post_delete"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", views.post_detail, name="post_detail"),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/logout/', auth_views.LogoutView.as_view(template_name="registration/logout.html"), name='logout'),
    path("accounts/", include("accounts.urls", namespace="accounts")),
    path("", include("blog.urls", namespace="blog")),
    path("about/", TemplateView.as_view(template_name="about.html")),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from django.utils.text import slugify

from taggit.managers import TaggableManager

# Create your models here.
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date=("publish"))
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="blog_posts")
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)

    objects = models.Manager() # The default manager
    published = PublishedManager() # Our Custom manager

    tags = TaggableManager() # Third-party manager

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]


    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse("blog:post_detail", args=[self.publish.year,
                                                self.publish.month,
                                                self.publish.day,
                                                self.slug])
    



class Comment(models.Model):
    post = models.ForeignKey(Post,
                            on_delete=models.CASCADE, 
                            related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)


    class Meta:
        ordering = ["created"]
        indexes = [
            models.Index(fields=['created'])
        ]


    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment, Post

class PostForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ["title", "body", "tags"]

        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control border border-primary p-2 mb-2 border-opacity-75"}),
            "body": forms.Textarea(attrs={"class": "form-control border border-primary p-2 mb-2 border-opacity-75"}),
            "tags": forms.TextInput(attrs={"class": "form-control border border-success p-2 mb-2 border-opacity-75"})
        }

class EmailPostForm(forms.Form):
    name = forms.CharField(
            max_length=25,
            widget=forms.TextInput(attrs={'class': "form-control border border-success p-2 mb-2 border-opacity-75",'placeholder': "John Doe"}), 
            label="Name")
    email = forms.EmailField(
            widget=forms.EmailInput(attrs={"class": "form-control border border-success p-2 mb-2 border-opacity-75", 'placeholder': "sender@gmail.com"}),
            label="Email")
    to = forms.EmailField(
            widget=forms.EmailInput(attrs={"class": "form-control border border-success p-2 mb-2 border-opacity-75", 'placeholder': "receiver@gmail.com"}),
            label="To")
    comments = forms.CharField(
            required=False,
            widget=forms.Textarea(attrs={"class": "form-control border border-success p-2 mb-2 border-opacity-75", 'placeholder': "Your thoughts..."}), 
            label="Comment")


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ["name", "email", "body"]

        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border border-primary p-2 mb-2 border-opacity-75", "placeholder": "John Doe"}),
            "email": forms.EmailInput(attrs={"class": "form-control border border-primary p-2 mb-2 border-opacity-75", "placeholder":"john@gmail.com"}),
            "body": forms.Textarea(attrs={"class": "form-control border border-primary p-2 mb-2 border-opacity-75", "placeholder": "Share your thoughts..."}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseForbidden
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm, PostForm
from django.contrib.auth.decorators import login_required

from taggit.models import Tag
from django.db.models import Count
from django.utils.text import slugify

from django.core.mail import send_mail
from django.views.decorators.http import require_POST

from django.views.generic import ListView

# Create your views here.
def post_list(request, tag_slug=None):
    post_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_list = post_list.filter(tags__in=[tag])
    # Pagination with 3 posts per page
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get("page", 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # If page_number is not a integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page_number is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, "blog/post/list.html", {'posts':posts, "tag":tag})

@login_required
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post,
                            status=Post.Status.PUBLISHED,
                            slug=post,
                            publish__year=year,
                            publish__month=month,
                            publish__day=day)
    
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    # Form for users to comment
    form = CommentForm()

    # List of similar posts
    post_tags_id = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_id).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by("-same_tags", "-publish")[:4]

    return render(request,
                "blog/post/detail.html",
                {"post": post, 
                "comments": comments, 
                "form": form,
                "similar_posts": similar_posts})

@login_required
def post_share(request, post_id):
    # Retrieve post by id 
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == "POST":
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields pass validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recommends you read {post.title}"
            message = f"Read {post.title} at {post_url}\n\n{cd['name']}'s comments: {cd['comments']}"
            send_mail(
                subject=subject,
                message=message,
                from_email="ahmadfarazjanjua780@gmail.com",
                recipient_list=[cd['to']]
                )
            sent = True
    else:
        form = EmailPostForm()
    
    return render(request, "blog/post/share.html", {"post": post, "form": form, "sent": sent})


@require_POST
@login_required
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    # A comment was posted
    form = CommentForm(request.POST)
    if form.is_valid():
        # Create a comment object without saving it to database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = post
        # Save the comment to database
        comment.save()

    return render(request, "blog/post/comment.html", {"post":post, "form": form, "comment":comment})


# --------------------------------------Adding CRUD Functionality------------------------------------

# Create View
@login_required
def post_create(request):
    if request.method == "POST":
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.status = Post.Status.PUBLISHED
            post.slug = slugify(post.title)
            post.save()
            form.save_m2m()  # Save the tags
            return redirect("blog:post_detail", post.publish.year, post.publish.month, post.publish.day, post.slug)
        
    else: 
        form = PostForm()

    return render(request, "blog/post/post_form.html", {"form":form})


@login_required
def post_update(request, id):
    post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)

    if post.author != request.user:
        return HttpResponseForbidden()
    
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)

        if form.is_valid():
            post = form.save(commit=False)
            post.status = Post.Status.PUBLISHED
            if not post.slug:
                post.slug = slugify(post.title)
            post.save()
            form.save_m2m() # Save the tags
            return redirect("blog:post_detail", post.publish.year, post.publish.month, post.publish.day, post.slug)
        
    else: 
        form = PostForm(instance=post)
    
    return render(request, "blog/post/post_form.html", {"form":form, "post": post})

@login_required
def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    if post.author != request.user:
        return HttpResponseForbidden()

    if request.method == 'POST':
        post.delete()
        return redirect('blog:post_list')

    return render(request, 'blog/post/post_confirm_delete.html', {'post': post})

class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = "posts"
    paginate_by = 3
    template_name = "blog/post/list.html"

blog/templates/blog/base.html
{% load custom_tags %}
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock title %}</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />

        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static "css/styles.css" %}">
    </head>

    <body>
        <header>
            <!-- place navbar here -->
            <nav
                class="navbar navbar-expand-sm navbar-dark bg-dark"
            >
                <div class="container">
                    <a class="navbar-brand" href="/">ThoughtCanvas</a>
                    <button
                        class="navbar-toggler d-lg-none"
                        type="button"
                        data-bs-toggle="collapse"
                        data-bs-target="#collapsibleNavId"
                        aria-controls="collapsibleNavId"
                        aria-expanded="false"
                        aria-label="Toggle navigation"
                    >
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="collapsibleNavId">
                        <ul class="navbar-nav me-auto mt-2 mt-lg-0">
                            <li class="nav-item">
                                <a class="nav-link active" href="/" aria-current="page"
                                    >Home
                                    <span class="visually-hidden">(current)</span></a
                                >
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="/about">About</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link active" href="{% url "blog:post_create" %}">New</a>
                            </li>
                        </ul>
                        <div class="d-flex align-items-center ms-auto">
                            {% if user.is_authenticated %}
                                <p class="text-white mb-0 me-3">Hi {{ user.username }}</p>
                                <a class="btn btn-success me-2" href="{% url 'logout' %}">Log out</a>
                            {% else %}
                                <a class="btn btn-success me-2" href="{% url 'accounts:signup_view' %}">Sign Up</a>
                                <a class="btn btn-primary" href="{% url 'accounts:login' %}">Login</a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </nav>
            
        </header>
        <main>
            <div class="container">
                {% block about %}
                    <div class="row">
                        <div class="col-md-8">
                            {% block content %}
                            {% endblock content %}
                        </div>
                        <div class="col-md-4 bg-body-secondary">
                            <h2>My blog</h2>
                            <p>
                                Blog have {% total_posts %} posts so far 
                                {% if user.is_authenticated %}
                                    and You've written {% total_user_posts request.user %} posts so far.
                                {% endif %}
                            </p>
                            <h3>Latest Posts</h3>
                            {% show_latest_posts 3 %}

                            <h3>Most commented posts</h3>
                            {% get_most_commented_posts as most_commented_posts %}
                            <ul>
                                {% for post in most_commented_posts %}
                                    <li>
                                        <a href="{{post.get_absolute_url}}">{{post.title}}</a>
                                    </li>
                                {% endfor %}
                            </ul>
                            {% block sidebar %}
                            
                            {% endblock sidebar %}
                        </div>
                    </div>
                    {% include "pagination.html" %}
                {% endblock about %}
            </div>
        </main>

        <footer class="py-3 my-4 ">
            <!-- place footer here -->
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="/blog" class="nav-link px-2 text-muted">Home</a></li>
                <li class="nav-item"><a href="/about" class="nav-link px-2 text-muted">About</a></li>
            </ul>
            <p class="text-center text-muted">&copy; 2024 Company, Inc</p>
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>